{  
   "cookies":[  
      "deu-lhe um biscoito de chocolate!",
      "deu-lhe um biscoito caseiro de aveia!",
      "deu-lhe um biscoito podre e sujo. Era o último do pacote. Que nojo!",
      "deu-lhe um bolinho de açúcar. O quê? Sem estrelinhas e povilho? Eu não tocaria.",
      "deu-lhe um biscoito de chocolate. Oh, não, são passas. Eca!",
      "deu-lhe um enorme biscoito. Quando o toca, mais biscoitos aparecem. Estranho.",
      "deu-lhe um biscoito da sorte, tem escrito: \"Por que você não está trabalhando?\"",
      "deu-lhe um biscoito da sorte, tem escrito: \"Cumprimente agora a pessoa que você ama\"",
      "deu-lhe um biscoito da sorte, tem escrito: \"Arrisque-se!\"",
      "deu-lhe um biscoito da sorte, tem escrito: \"Vai dar uma volta.\"",
      "deu-lhe um biscoito da sorte, tem escrito: \"Não esqueça de comer os vegetais\"",
      "deu-lhe um biscoito da sorte, tem escrito: \"Você levanta mesmo?!\"",
      "deu-lhe um biscoito da sorte, tem escrito: \"Seje menas\"",
      "deu-lhe um biscoito da sorte, tem escrito: \"Se você mexer o quadril, você vai pegar todas as garotas!\"",
      "deu-lhe um biscoito da sorte, tem escrito: \"Eu te amo\"",
      "deu-lhe um biscoito de ouro. Não dá pra comer... Droga!",
      "deu-lhe um Oreo e um copo de leite.",
      "deu-lhe um biscoito arco-íris feito com amor :heart:",
      "deu-lhe um biscoito que foi esquecido na chuva... e está mofado.",
      "te trouxe biscoitos fresquinhos... parecem deliciosos!"
   ],
   "perguntas":[  
      "Havia dois ursos o Beijaeu e o Mebeija, o Beijaeu morreu quem sobrou?",
      "Eu perdi o número do meu telefone… Me empresta o seu?",
      "Estou fazendo uma campanha de doação de órgãos! Não quer doar seu coração pra mim?",
      "Gata (o), você é sempre gostosa assim ou hoje tá fantasiada de lasanha?",
      "Você acredita em amor à primeira vista ou devo passar por aqui mais uma vez?",
      "Me passa o seu Twitter? O meu pai disse que eu devo seguir o meu sonho.",
      "Sua mãe é uma ostra???? Como pode ter uma pérola assim em casa?",
      "Você precisa de um doador de órgãos???? Porque te dou meu coração!",
      "Além de ser linda, simpática, perfumada, gente boa e gostosa o que mais você faz?",
      "Se eu fosse um papel, você me daria uns amassos?",
      "Pra que carnaval em Salvador se eu tenho você aqui?",
      "Me empresta um beijo? juro que devolvo.",
      "Gata(o), vamos marcar um dia pra ir no cinema e não assistir o filme ?",
      "O que vai fazer hoje? Nada? Que tal fazermos nada juntos?",
      "Seu nome é mentira? Você é muito linda pra ser verdade.",
      "Você gosta de canto? Sim? Então vamos para aquele ali?",
      "Eu + você + beijos + abraços = Quando?",
      "Tem um brigadeiro e um bejinho em cima da mesa. O brigadeiro rolou e caiu. E o beijinho, será que rola?",
      "Desculpa, eu não sou daqui mas queria saber, onde fica a estrada que leva para o seu coração?",
      "Existe um vazio no meu coração que tem as suas medidas. Quer entrar?"
   ],
   "mito":[  
      "Música mais zika que o MC Silvio Santos!",
      "Que música mais deliciosa que uma Marmitex!",
      "Q U A L I D A D E & S I N C R O N I A",
      "Sem essa música, a vida seria um erro.",
      "Acho que ejaculei ao ouvir isso.",
      "Orgasmos estão vindo a tona.",
      "Sua música me deu tanto prazer quanto a Mia Khalifa!",
      "Essa música é tão boa que me deu vontade de Fritar!",
      "Essa música é das boas, ótima escolha!",
      "Essa música é tão boa que eu to dançando em cima da Mesa!",
      "Essa música me levou as 128bpm, que sensação :heart: !",
      "Essa música tem uma Batida Sensacional!",
      "Essa música é tão boa, que só os Loucos Sabem!",
      "Essa música é tão boa que até os 12 universos adoram ela!",
      "Qualificado, Sua música é tão boa que Cromulon a cabeça Alien Adorou!",
      "Essa música é tão boa que eu Addedei de novo!"
   ],
   "hino":[  
      "Um HINO desses, bixo :hino: ",
      "Essa música é tão Top que eu to no chão!",
      "Essa música ♥, Requebrei!",
      "Arrastei a raba no chão ouvindo essa música",
      "Arrasou na escolha",
      "Um tiro doeria menos",
      "Que tiro de música, bb",
      "Se prepara, vou dançar, preste atenção ham ham",
      "Arrasou amore ❤",
      "Anotei essa musica aqui, amore 📝",
      "O problema dessa música é que ela acaba",
      "Hmmm essa música é de dar água na boca 👄"
   ],
   "lixo":[  
      "Música mais lixo que minha vida!",
      "A melhor parte dessa musica é quando ela acaba",
      "Poha de barulho é esse?",
      "Música mais merda que minha internet!",
      "Essa música é tão lixo, como eu tentar usar hack na roleta!",
      "Música mais repetitiva do quê a galera gritando \"QUE HINOO\" na sala!",
      "Essa música só não é a pior coisa do mundo porque existe o tal do funk!",
      "Pisei numa merda, sua música!",
      "Música mais lixo que o Felipe Neto!",
      "As definições de música lixo foram atualizadas!",
      "Eu estava até gostando de você, mas depois dessa música acabou a amizade!",
      "Essa música foi tão ruim que me deu câncer.",
      "Se essa música fosse boa se chamaria  \"Mulheres\"!",
      "Até KPOP é melhor que isso.",
      "Deixa o Burkyst na sala mas tira isso, por favor.",
      "Parabéns pela coragem de tocar isso, porque noção não tem!",
      "Música tão enjoativa quanto ao comercial da Trivago!"
   ],
   "seduzir":[  
      "Nenhuma placa de vídeo, poderia renderizar os 100% da sua beleza",
      "Para tirar você da cabeça, só formatando!",
      "Meu amor por você é um loop infinito!",
      "Gata (o), você tem acesso root ao meu coração.",
      "Sem você meu coração é null.",
      "Gata (o), me passa o seu IP para eu fazer uma conexão remota com o seu coração... Seu linda (o)!",
      "Gata (o), Ate_meu_aquivo_quer_que_voce.mpeg",
      "Entre tantas variáveis, você é uma constante no meu coração.",
      "Você é o CSS do meu código HTML.",
      "Gata (o), perto de você, eu sou como o Internet Explorer. Só de olhar pra mim que eu já travo.",
      "Gata (o) você nao é baidu Antisvirus, mas se instalou no meu coração e eu não consigo mais remover.",
      "Gata(o) eu não sou o Finn , mais viveria muitas aventuraras por vc.",
      "Você não é garçonete, mas já serve!",
      "Me chama de sal grosso, que eu me atiro nas tuas carnes!",
      "Me chama de luneta que eu te faço ver estrelas.",
      "Gata (o), você não é beliche, mas tem dois coxão!",
      "Quando Deus te desenhou, ele usou o Photoshop CS6.",
      "CMYKÉ? Vem MPEGar.",
      "Queria ser seu suor, para correr por todo o seu corpo.",
      "Me chama de jedi que te ensino a mexer no meu sabre de luz :new_moon_with_face:",
      "Não tenho 7 esferas do dragão mas com 2 satisfaço seu desejo :new_moon_with_face:",
      "Eu não sou cachoeira mas tenho uma queda por você :new_moon_with_face:",
      "Eu não sou jedi mas posso te fazer sentir a força :new_moon_with_face:",
      "Eu não sou o pikachu, mas prometo que quando eu te beijar vai ser chocante :new_moon_with_face:",
      "Mal te conheço, mas já sei só você é digna de levantar o meu martelo :new_moon_with_face:",
      "Posso ser nub no LOL , mas por você encaro a mid sem pensar duas vezes :new_moon_with_face:",
      "Você é o papa léguas? porque é difícil de pegar, hein :new_moon_with_face:",
      "Você gosta de criança? porque eu sei fazer :new_moon_with_face:",
      "Convidou você para comer tomate com sal",
      "Pesquisas apontam que voce viu a super lua, mas nao vê o super mole que eu te dou...:new_moon_with_face:",
      "Te desejo um par de lentes de contato, que façam você ter olhos pra mim :new_moon_with_face:",
      "Me chama de academia, e me faz...:new_moon_with_face:",
      "Se voce fosse refrigerante, seria SODA, porque no meu coração, SODA você :kissing_heart:",
      "Chama a polícia, que eu vou roubar uns beijos seu :kiss:",
      "Não sou traficante, mas eu quero a sua boca :smirk:",
      "Eu não sou a Casas Bahia, mas prometo dedicação total a você :kissing_heart:",
      "Estou fazendo uma campanha de doação de órgãos! Não quer doar seu coração pra mim? :gift_heart:",
      "Você não é pescoço mais mexeu com a minha cabeça! :kissing_heart:",
      "Gata, você não é rocambole, mas eu daria tudo para ficar enroladinho :kissing_heart:",
      "Gata sua calcinha não é download mas bem que eu queria baixar. :new_moon_with_face:",
      "Me joga no Google, me chama de pesquisa, e diz que eu sou tudo o que você procurava! :kissing_heart:",
      "Não sou o Luciano Hulk mas bora partir pro AGORA ou NUNCA? :new_moon_with_face:",
      "Vem brincar de suor e correr por todo meu corpo. SEU LINDO! :new_moon_with_face:",
      "Me chama de destino e me traça SEU LINDO! :new_moon_with_face:",
      "Me chama de Black Eyed Peas e vem fazer um bom bom pow na cama comigo SEU LINDO! :new_moon_with_face:",
      "Você é que nem hino nacional, grande e dificil de cantar! :eyes:",
      "Não sei qual é a sua comida preferida mas eu posso ser ela FACIL! :new_moon_with_face:",
      "Voce pode até ser rico que eu faço voce ficar duro rapidinho :new_moon_with_face:",
      "Se gostar a gente pode brincar de pelada, aí voce faz um gol na minha grande área! bora ? :new_moon_with_face:",
      "Vem pintar de branco a parede do meu útero! :new_moon_with_face:",
      "Você nao é o bob esponja mas eu deixo voce morar na fenda do meu biquine seu lindo! :kissing_heart:",
      "Se eu me afogar na tua beleza tenho direito a respiração boca a boca? :new_moon_with_face:",
      "Vai ser linda assim lá na… rua de mãos dadas comigo fazendo inveja para os meus amigos :kissing_heart:",
      "Você conhece os sete pecados? Prazer, eu sou o oitavo :kissing_heart:",
      "Você não é combustível Petrobras, mas é meu sonho de consumo! :kissing_heart:",
      "Gata, a vida imita a arte, e a arte imita você… :kissing_heart:",
      "Preciso voltar a estudar mitologia grega, porque essa deusa eu não conhecia ainda! :kiss:",
      "Gata, você é a figurinha que falta no meu álbum. Cola em mim que a gente se completa, SUA LINDA :heart:",
      "Gata, me chama de imposto de renda e se declara pra mim, SUA LINDA"

   ],
   "tretas": [
      "Te deu uma voadora",
      "Deu um tapa na sua cara :punch:",
      "Deu uma rasteira,em seguida pisou nas suas... :soccer:",
      "Veio correndo e com os dois pés acertou seu estômago :dizzy_face:",
      "Puxou seu cabelo :snake:",
      "Te deu um pedala robinho :blush:",
      "Veio correndo,se preparou para a voadora e...escorregou que pena :cry:",
      "Pegou o chinelo e te bateu :hushed:",
      "Puxou a cinta e deu na sua bunda :scream: :lenny:"
   ],
   "balls":[  
      "Sinais apontam que sim.",
      "Sim.",
      "Tente novamente mais tarde.",
      "Sem d\u00favidas.",
      "Minhas fontes dizem que n\u00e3o.",
      "Ao meu ver, sim.",
      "Pode contar com isso.",
      "Concentre-se e pergunte novamente.",
      "Acho que n\u00e3o.",
      "Definitivamente.",
      "Melhor n\u00e3o te falar...",
      "\u00c9 duvidoso.",
      "Sim. Definitivamente!",
      "\u00c9 certo.",
      "N\u00e3o posso prever agora.",
      "Provavelmente.",
      "Pergunte-me depois.",
      "Minha resposta \u00e9 n\u00e3o.",
      "Parece bom.",
      "N\u00e3o conte com isso.",
      "Sim, em seu devido tempo.",
      "Minhas fontes dizem que n\u00e3o.",
      "Definitivamente n\u00e3o.",
      "Voc\u00ea vai ter que esperar...",
      "Eu tenho minhas d\u00favidas.",
      "Um tanto...",
      "Parece bom para mim!",
      "Quem sabe?",
      "Claro!",
      "Provavelmente.",
      "Est\u00e1 brincando?",
      "N\u00e3o aposte nisso.",
      "Você acha que tenho bola de cristal?",
      "Vai se ferrar, para de me fazer perguntas.",
      "Não sei, pergunta no posto Ipiranga",
      "Esque\u00e7a..."
   ],
   "jokenpobot": [
      "Pedra",
      "Tesoura",
      "Papel"
   ],

   "Dares": [
      "Posalji srce osobi koje je trenutno DJ.",
      "Otici ces u neku drugu zajednicu gdje govore bos/srb/hrv jezik i napisat ces -da li je neko za vezu-",
      "Pustit ces pjesmu koja ima izazovniji spot.",
      "Moras nacrtat ces u paintu nesto za osobu koja se nalazi u ovoj sobi.",
      "Moras da ispricas izazovniji vic sad.",
      "Poslat ces -vtp- prvoj osobi koja je na lisit cekanja.",
      "Moras izaci iz liste cekanja."
   ],
   "Truths": [
      "Da li te iko ikada video potpuno golu/og. Ako da, ko?",
      "Šta je najgluplja stvar koju ste učinili pred nekim?",
      "Da li si ikada pišao/la u bazenu?",
      "Da li si se ikad zaljubila/o u devojku/dečka svog prijatelja?",
      "Šta je najneugodnija stvar koju si ikad učinio u svom životu?",
      "Koju stvar si uradio, a nisi želio da ikada budeš uhvaćen u njoj?",
      "Ko je bio tvoja prva simpatija, ili ko je trenutno?",
      "Koliko ste imali godina kada ste imali svoj prvi poljubac?",
      "Da li ste ikada prevarili dečka / devojku?",
      "Ako bi mogao s nećim otići na sastanak, s kim bi to bilo?",
      "Jeste li ikada lagali svog najboljeg prijatelja?",
      "Ako ste se zaglavili na pustom otoku, kojeg prijatelji bi zeljeli da bude sa vama?",
      "Koliko vremena je prošlo od tvog zadnjeg tuširanja?",
      "Šta je ono što ne želiš da te iko ovde pita? (Budite sigurni da to treba imati na umu za buduće runde!)",
      "Jesi li ikada lagao tokom igranja ovoga !truth? Ako jesi, šta si lagao, i zašto?",
      "Da li vam se iko sviða u ovoj sobi kao dečko/devojka?",
      "Jeste li ikad ukrali nešto?"
   ],
   "nodatafound":"Dados anteriores não encontrados.",
   "currentlang":"/me Idioma definido: %%LANGUAGE%%",
   "langerror":"/me O idioma que você selecionou não está disponível. Liste de idiomas disponíveis: %%LINK%%",
   "langset":"/me Idioma definido para: %%LANGUAGE%%",
   "retrievingdata":"Recuperando dados armazenados anteriormente.",
   "datarestored":"Dados armazenados anteriormente recuperados com êxito.",
   "greyuser":"Apenas Seguranças ou superiores podem usar o bot.",
   "bouncer":"O bot não pode mover pessoas na fila de espera quando usado por um bouncer.",
   "online":"/me %%BOTNAME%% v%%VERSION%% online!",

   "welcome":"\/me :hearts: Bem vindo(a), @%%NAME%%! Tema: %%TEMA%%",
   "welcomeback":"\/me :v: Bem vindo(a) de volta, %%NAME%%! Tema: %%TEMA%%",

   "songknown":"@%%NAME%%, essa música está no histórico.",
   "notavailable":"/me @%%NAME%%, a música que você tocou não está disponível.",
   "timelimit":"@%%NAME%%, sua música tem duração maior que %%MAXLENGTH%% minutos. ela será pulada após esse tempo!",
   "skiptime":"@%%NAME%%, limite de  %%MAXLENGTH%% minutos excedido. Pulando...",
   "permissionownsong":"/me :up: @%%NAME%% tem permissão para tocar música de própria autoria!",
   "isblacklisted":"/me Essa música está na blacklist %%BLACKLIST%%! Pulando música...",
   "isopen":"/me :sound: A roleta do batidão foi iniciada! :sound: Use !join para entrar @djs (Jogo onde um participante aleatório é movido para a posição %%POS%% na fila de espera)",
   "setRoleta":"/me [@%%NAME%%] Posição da Roleta alterada para: %%POS%%",
   "killtroll":"/me [@%%NAME%%] Roleta desativada.",
   "winnerpicked":"/me Pelo visto @%%NAME%% pró em twerk ganhou posição %%POSITION%%. :twerk:",
   "ball":"/me A pergunta de %%NAME%% foi: \"%%QUESTION%%\" e a resposta de %%BOTNAME%% é: \"%%RESPONSE%%\"",
   "notghosting":"[%%NAME1%%] %%NAME2%% não virou fantasma.",
   "ghosting":"[%%NAME1%%] %%NAME2%% deve ter virado fantasma.",
   "duelTime":"/me [@%%NAME%%] MUTE do Duel alterado para: %%TIME%% minutos.",
   "alreadyadding":"/me Usuário já está sendo adicionado! Posição desejada alterada para %%POSITION%%.",
   "adding":"/me @%%NAME%% foi adicionado à fila. Posição atual: %%POSITION%%.",
   "usernotfound":"/me Usuário não encontrado.",
   "notdisconnected":"/me @%%NAME%% não tem se desconectado durante meu tempo aqui.",
   "noposition":"/me Última posição não reconhecida. A fila de espera precisa ser atualizada pelo menos uma vez para registrar posições.",
   "toolongago":"/me @%%NAME%%'s desconectou-se a muito tempo atrás: %%TIME%%.",
   "valid":"/me @%%NAME%% desconectou-se %%TIME%% atrás e deve ter posição %%POSITION%%.",
   "warning1":"@%%NAME%%, você esteve inativo por %%TIME%%, responda dentro de 2 minutos ou você será removido da fila de espera.",
   "warning2":"@%%NAME%%, você será removido em breve por inatividade se não responder.",
   "afkremove":"/me @%%NAME%%, você foi removido da fila de espera por estar AFK por %%TIME%%. Você esteve na posição %%POSITION%%. Use o chat pelo menos a cada %%MAXIMUMAFK%% minutos se quiser tocar uma música.",
   "caps":"@%%NAME%%, desligue seu capslock, por favor.",
   "askskip":"@%%NAME%%, não peça skips.",
   "spam":"/me @%%NAME%%, não faça spam, por favor.",
   "roomadvertising":"@%%NAME%%, não poste link de outras comunidades, por favor.",
   "adfly":"@%%NAME%%, por favor mude seu script autowoot. Nós sugerimos plugCubed: http://plugcubed.net/",
   "validgiftags":"/me [@%%NAME%%] [Tags: %%TAGS%%] http://i.giphy.com/%%ID%%.gif",
   "invalidgiftags":"/me [@%%NAME%%] [Tags: %%TAGS%%] Tag inválida, tente algo diferente.",
   "validgifrandom":"/me [@%%NAME%%] [GIF randômica] http://media.giphy.com/media/%%ID%%/giphy.gif",
   "invalidgifrandom":"/me [@%%NAME%%] Instância inválida, tente novamente.",
   "invalidtime":"/me [@%%NAME%%] Tempo inválido.",
   "nouserspecified":"/me [@%%NAME%%] Usuário não especificado.",
   "invaliduserspecified":"/me [@%%NAME%%] Usuário inválido.",
   "nolistspecified":"/me [@%%NAME%%] Lista não especificada.",
   "invalidlistspecified":"/me [@%%NAME%%] Lista inválida.",
   "novaliduserspecified":"/me [@%%NAME%%] Usuário especificado não válido.",
   "nolimitspecified":"/me [@%%NAME%%] Limite não especificado.",
   "invalidlimitspecified":"/me [@%%NAME%%] Limite inválido.",
   "invalidpositionspecified":"/me [@%%NAME%%] Posição inválida.",
   "whois":"/me [%%NAME1%%] Usuário: %%NAME2%%, ID: %%ID%%, Rank: %%RANK%%, Registro: %%JOINED%%, Nível: %%LEVEL%%, Linguagem: %%LANGUAGE%%, Avatar: %%AVATAR%%, Perfil: %%PROFILE%%",
   "id":"/me [@%%NAME2%%] Seu ID é: %%ID%%",
   "slotready":"/me [@%%NAME2%%] Tempo do slots corrigido ",
   "toggleon":"/me [@%%NAME%%] %%FUNCTION%% ativado.",
   "toggleoff":"/me [@%%NAME%%] %%FUNCTION%% desativado.",
   "cmddeletion":"remoção de comandos",
   "afkremoval":"Remoção de AFK",
   "afksremoved":"AFKs removidos",
   "afklimit":"Limite AFK",
   "autodisable":"autodisable",
   "autoskip":"autoskip",
   "newblacklisted":"/me [@%%NAME%%] Essa música está na lista negra %%BLACKLIST%%! [ %%AUTHOR%% - %%TITLE%% - %%MID%% ]",
   "blinfo":"[@%%NAME%%] Info da Blacklist - autor: %%AUTHOR%%, título: %%TITLE%%, ID: %%SONGID%%",
   "blacklist":"blacklist",
   "cycleguard":"cycleguard",
   "timeguard":"timeguard",
   "chatfilter":"chatfilter",
   "historyskip":"historyskip",
   "lockdown":"lockdown",
   "lockguard":"lockguard",
   "usercommands":"comandos de usuário",
   "motd":"MotD",
   "welcomemsg":"mensagem de boas vindas",
   "songstats":"estatísticas de música",
   "etarestriction":"restrição de ETA",
   "voteskip":"voteskip",
   "voteskiplimit":"/me [@%%NAME%%] Limite de voteskip é, no momento, %%LIMIT%% mehs.",
   "voteskipexceededlimit":"/me @%%NAME%%, sua música excedeu o limite de (%%LIMIT%% mehs).",
   "voteskipinvalidlimit":"/me [@%%NAME%%] Limite de voteskip inválido, por favor, tente novamente usando um número válido para indicar o número de mehs.",
   "voteskipsetlimit":"/me [@%%NAME%%] Limite de voteskip definido para %%LIMIT%%.",
   "activeusersintime":"/me [@%%NAME%%] %%AMOUNT%% usuários estiveram ativos nos últimos %%TIME%% minutos.",
   "maximumafktimeset":"/me [@%%NAME%%] Duração máxima de AFK agora é: %%TIME%% minutos.",
   "afkstatusreset":"/me [@%%NAME%%] Status AFK resetado: @%%USERNAME%%.",
   "inactivefor":"/me [@%%NAME%%] @%%USERNAME%% esteve inativo por %%TIME%%.",
   "inactivelonger":"/me [@%%NAME%%] @%%USERNAME%% esteve inativo por mais tempo que %%BOTNAME%% esteve online.",
   "autowoot": "\/me N\u00f3s recomendamos RCS para autowoot",
   "brandambassador":"/me Um Embaixador de Marca é a voz dos usuários da plug.dj. Eles promovem eventos, ajudam as comunidades e divulgam a plug.dj para todo o mundo. Mais info: https://plug.dj/ba",
   "bouncerplusrank":"/me [@%%NAME%%] Você precisa ser Coordenador ou superior para ativar o Bouncer+.",
   "rdjplusrank":"/me [@%%NAME%%] Você precisa ser Coordenador ou superior para ativar o RDJ+.",
   "chatcleared":"/me [@%%NAME%%] O chat foi limpo.",
   "deletechat":"/me [@%%NAME%%] O chat de %%USERNAME%% foi limpo.",
   "commandslink":"/me Comandos do %%BOTNAME%%: %%LINK%%",
   "eatcookie":"/me ama cookies.",
   "nousercookie":"/em Não vejo %%NAME%% na sala. Vou comer esse cookie sozinho.",
   "selfcookie":"/me @%%NAME%%, você é mesquinho, né? Dando cookies a si mesmo, bah. Compartilhe um pouco com os outros!",
   "cookie":"/me @%%NAMETO%%, %%NAMEFROM%% %%COOKIE%%",
   "botSeduzir":"/me Ama seduzir.",
   "nouserSeduzir":"/em Não vejo %%NAME%% na sala.",
   "selfSeduzir":"/me @%%NAME%%, Não pense somente em você, use o comando para seduzir alguém.",
   "seduzirs":"/me De: @%%NAMEFROM%%, Para: @%%NAMETO%%: %%SEDUZIR%%",
   "botPerguntar":"/me Ama Perguntar.",
   "nouserPerguntar":"/em Não vejo %%NAME%% na sala.",
   "selfPerguntar":"/me @%%NAME%%, Não faça perguntas a você mesmo, use o comando com outro usuário que não seja você!",
   "perguntar":"/me De: %%NAMEFROM%%, Para: %%NAMETO%%: %%PERGUNTAR%%",
   "cycleguardtime":"/me [@%%NAME%%] A proteção de ciclo agora é: %%TIME%% minuto(s).",
   "dclookuprank":"/me [@%%NAME%%] Somente Seguranças ou superiores podem usar !dclookup em outros usuários.",
   "emojilist": "/me Emotes RCS: https://moveitbrasil.tk/emotes - Emojis Plug: http://www.emoji-cheat-sheet.com/ ",
   "notinwaitlist":"@%%NAME%%, você não está na lista de espera.",
   "youarenext":"/me @%%NAME%%, você tocará depois desta música.",
   "youaredj":"/me @%%NAME%%, você está tocando.",
   "eta":"/me @%%NAME%%, você está na posição %%POSITION%% na fila de espera e tocará em aproximadamente %%TIME%%.",
   "facebook":"/me Entre em nosso grupo no Facebook: %%LINK%%",
   "starterhelp":"/me Essa imagem te ajudará a usar e entender o plug.dj: %%LINK%%",
   "jointime":"/me [@%%NAMEFROM%%] @%%USERNAME%% esteve na sala por %%TIME%%.",
   "jokenpo": "\/me Jokenpo: %%NAME%% jogou: \"%%QUESTION%%\" x %%BOTNAME%% jogou: \"%%RESPONSE%%\"",
   
   "roulettejoin":"/me @%%NAME%% entrou na roleta! (Use !leave para sair da mesma)",
   "isopenpp":"\/me :pp: A roleta do Silvão foi iniciada! :pp: Quem quer dinheiro? MAOE! Use !pp para entrar @djs",
   "isopenpp2":"\/me :airplane: (Olha o aviãozinho) :airplane: ",
   "winnerpickedpp":"\/me :airplane: O aviãozinho foi para @%%NAME%% que acaba de ganhar a rodada. :pp:",
   "rouletteppentra":"\/me @%%NAME%% entrou na roleta!  :airplane: Boa Sorte  (Use !sair para sair da mesma.):airplane: ",
   "rouletteppsair":"\/me  Temos um riquinho aqui, @%%NAME%% saiu da roleta!",
   "winnernull": "\/me Que pena, ninguem participou da roleta! O ganhador iria para a posi\u00e7\u00e3o %%POSITION%%.",
   "djwon": "\/me @%%NAME%% você ganhou a roleta enquanto estava tocando, se persistir sua punição será agravada!",

   "kickrank":"/me [@%%NAME%%] Você não pode kickar alguém do mesmo rank ou superior!",
   "kick":"[@%%NAME%%], @%%USERNAME%% você está sendo kickado da comunidade por %%TIME%% minutos.",
   "kill":"/me Desligando...",
   "logout":"/me [@%%NAME%%] Deslogando %%BOTNAME%%",
   "rouletteleave":"/me @%%NAME%% deixou a roleta!",
   "songlink":"/me [@%%NAME%%] Link para a música atual: %%LINK%%",
   "usedlockskip":"/me [%%NAME%% usou 'lockskip']",
   "usedskip":"/me [%%NAME%% usou skip]",
   "skippos":"/me [@%%NAME%%] DJs agora serão movidos para a posição %%POSITION%% quando forem pulados.",
   "lockguardtime":"/me [@%%NAME%%] A proteção de travamento agora é %%TIME%% minuto(s).",
   "maxlengthtime":"/me [@%%NAME%%] A duração máxima de tempo agora é %%TIME%% minutos.",
   "motdset":"/me Mensagem do Dia:  %%MSG%%",
   "motdintervalset":"/me Intervalo da Mensagem do Dia: %%INTERVAL%% músicas.",
   "currentbotname":"/me Nome do bot definido como: %%BOTNAME%%",
   "botnameset":"/me O nome do bot foi definido agora para: %%BOTNAME%%",
   "addbotwaitlist":"/me @%%NAME%%, não tente me adicionar à fila de espera, por favor.",
   "move":"/me [%%NAME%% usou 'move']",
   "mutednotime":"/me [@%%NAME%%] @%%USERNAME%% mutado.",
   "mutedmaxtime":"/me [@%%NAME%%] Você só pode mutar até no máximo %%TIME%% minutos.",
   "mutedtime":"/me [@%%NAME%%] @%%USERNAME%% mutado por %%TIME%% minuto(s).",
   "unmuted":"/me [@%%NAME%%] @%%USERNAME%% desmutado.",
   "muterank":"/me [@%%NAME%%] Você não pode mutar usuários do mesmo nível ou superior.",
   "oplist":"/me Consulte as músicas que estão na nossa Blacklist: %%LINK%%",
   "pong":"/me Pong!!",
   "reload":"/me Reiniciando...",
   "removenotinwl":"/me [@%%NAME%%] Usuário @%%USERNAME%% não está na fila de espera.",
   "roomrules":"/me Encontre as regras da sala aqui: %%LINK%%",
   "sessionstats":"/me [@%%NAME%%] Quantidade total de woots: %%WOOTS%%, mehs: %%MEHS%%, grabs: %%GRABS%%.",
   "forceskip":"/me [%%NAME%% usou forceskip]",
   "madeby":"/me Este bot foi feito por %%NAME%%.",
   "activefor":"Estive online por %%TIME%%.",
   "swapinvalid":"/me [@%%NAME%%] Usuário inválido.",
   "swapwlonly":"/me [@%%NAME%%] Use !swap somente com usuários que estão na fila de espera.",
   "swapping":"/me Trocando posições: %%NAME1%% com %%NAME2%%.",
   "genres":"/me %%LINK%%",
   "notbanned":"/me [@%%NAME%%] Usuário mencionado não foi banido.",
   "unmutedeveryone":"/me [@%%NAME%%] Todos foram desmutados.",
   "unmuteeveryonerank":"/me [@%%NAME%%] Somente Coordenadores podem desmutar todos os usuários de uma vez.",
   "notmuted":"/me [@%%NAME%%] Usuário mencionado não foi mutado.",
   "unmuterank":"/me [@%%NAME%%] Você não pode desmutar usuários do mesmo rank ou superior.",
   "commandscd":"/me [@%%NAME%%] O tempo de espera de comandos para usuários agora é %%TIME%% segundos.",
   "voteratio":"/me [@%%NAME%%] @%%USERNAME%% ~ woots: %%WOOT%%, mehs: %%MEHS%%, taxa/proporção (w/m): %%RATIO%%.",
   "website":"/me Visite nosso site: %%LINK%%",
   "youtube":"/me [%%NAME%%] Inscreva-se no nosso canal: %%LINK%%",
   "songstatistics":"/me %%ARTIST%% - %%TITLE%%: %%WOOTS%%W/%%GRABS%%G/%%MEHS%%M.",
   "jailsonVip": "\/me %%NAME%% é membro VIP e teve 20% a mais de chances de furar a fila",
   "jailsonNotClose":"\/me @%%NAME%% Deixa de ser cara de pau e entre na fila para depois tentar furar!",
   "jailsoncd":"\/me @%%NAME%% Que feio! Voce ainda não pode furar a fila, tente em %%TIME%% minutos.",
   "jailsonWorthy":"\/me @%%NAME%% Espertinho(a) conseguiu furar o 2º lugar na fila! :aww:",
   "jailsonNotWorthy":"\/me @%%NAME%% Que mal educado(a) tentando furar fila!!! Volte já para o final. :blobtriumph:",
   "chattersEmpty": "/me @%%NAME%% se você não fala nada, muito menos o bot. Na próxima, digite algo na sua mensagem.",
   "chattersFailed": "/me @%%NAME%% não foi possível enviar sua mensagem para o bot. Tente novamente.",
   "ssTitle":"SimSimi",
   "edTitle":"Robô ED",
   "adsTitle": "ADS BOT",
   "elTitle": "Elektra BOT",
   "cbTitle": "Cleverbot",
   "dicTitle": "Dicionário BOT",
   "sinTitle": "Sinônimo BOT",
   "urlTitle": "URL BOT",
   "cotTitle": "Cotação",
   "bcTitle": "BitCoin",
   "autoroleta":"Auto roleta",
   "setautoroleta":"Intervalo do AutoRoleta alterado para: %%AUR%% musicas.",
   "say":":email: Comunicado: %%QUESTION%% [ @everyone ]",
   "setInterval":"Intervalo de mensagens definido para: %%POS%%",
   "mitoChat":"[ @%%NAMEFROM%% ] relatou, \"%%MITO%%\" @%%NAMETO%%",
   "hinoChat":"[ @%%NAMEFROM%% ] relatou, \"%%HINO%%\" @%%NAMETO%%",
   "lixoChat":"[ @%%NAMEFROM%% ] relatou, \"%%LIXO%%\" @%%NAMETO%%",
   "automsg": "Mensagem Automática",
   "eattretar": "\/me Gosta de uma treta :treta:",
   "nousertretar": "\/em N\u00e3o vejo %%NAME%% na sala. Arranje briga com outra pessoa.",
   "selftretar": "\/me @%%NAME%%, Tretar sozinho não da,arrume confusão com alguém ai.",
   "tretar": "\/me @%%NAMETO%%, %%NAMEFROM%% %%TRETAR%%",
   "temaatual": "[@%%NAME%%] tema atual: %%TEMA%%",
   "settema": "[%%NAME%%] tema agora configurado para: %%TEMA%%",
   "rpslsempty": "\/me [game] [rps] Da bi igrao Rock Paper Scissors, koristi !rps {Choice}",
   "rpslserror": "\/me [error] Pogresan odabir, pokusaj ponovo!",
   "rpslswin": "[game] [rps] Pobjedio si i dobio nesto tokena %%NAME%%!",
   "rpslslose": "[game] [rps] Izgubio si %%NAME%%!",
   "rpslsdraw": "Nerjeseno je %%NAME%%!",
   "gameon": "/me @djs %%NAME%% Je pokrenuo PickTheNumber. Napiši broj od :one: do :nine:. Ukoliko te bot označi sa istim brojem koji si napisao pobedio si. Ukoliko ima više pobednika računa se onaj prvi koga je bot označio.",
   "trutherror": "/me [truth] %%NAME%% Greška... Pokušaj ponovo, verovatno si označio nekoga.",
   "truth": "/me [truth&dare ][truth] %%NAME%% %%FORTUNE%%",
   "trutherror": "/me [truth&dare] [!dare] %%NAME%% Greška... Pokušaj ponovo, ne mozes oznacavati nekoga. Izazov se daje samo tebi.",
   "dare": "/me [truth&dare] [dare] %%NAME%% %%FORTUNE%%",
   "stokens": "/me @%%NAME%%, Moras oznaciti kome zelis podijeliti tokene, zar ne?",
   "nousertokens": "/em [tokens] ne vidi %%NAME%% u sobi.",
   "selftokens": "/me [tokens] @%%NAME%%, Znam da bi bilo fora da sam sebi das tokene, mozda neki drugi put.",
   "giventokens": "/me [su] [tokens] @%%NAMEFROM%% je upravo dao @%%NAMETO%% nesto tokena da bi nastavio sa super muzikom.",
   "vdownload": "/me [!vdownload] @%%NAME%% Ovaj video možete skinuti ovde: %%LINK%%"
}